### ISSUE TITLE
Uncaught exception 'GearmanException' with message 'Failed to set exception option'

### ISSUE THREAD

**Issue by 4x4notfound** [brianlmoon/GearmanManager#42]
Wondering if you know why this issue would be caused by `$thisWorker->work()` ?

```
4703 DEBUG  Registering signals for parent
 4703 INFO   Loading workers in /var/www/GearmanManager/pecl-workers
 4703 INFO   Loading workers in /var/www/GearmanManager/pecl-worker-classes
 4705 PROC   Helper forked
 4705 INFO   Loading workers in /var/www/GearmanManager/pecl-workers
 4705 INFO   Loading workers in /var/www/GearmanManager/pecl-worker-classes
 4703 PROC   Started with pid 4703
 4703 PROC   Started child 4706 (reverse_string)
 4703 DEBUG  Registering signals for child
 4706 WORKER Adding server 127.0.1.1
 4706 WORKER Adding job reverse_string
 4703 PROC   Started child 4707 (reverse_string)
PHP Fatal error:  Uncaught exception 'GearmanException' with message 'Failed to set exception option' in /var/www/GearmanManager/pecl-manager.php:51
Stack trace:
#0 /var/www/GearmanManager/pecl-manager.php(51): GearmanWorker->work()
#1 /var/www/GearmanManager/GearmanManager.php(877): GearmanPeclManager->start_lib_worker(Array)
#2 /var/www/GearmanManager/GearmanManager.php(820): GearmanManager->start_worker('reverse_string')
#3 /var/www/GearmanManager/GearmanManager.php(250): GearmanManager->bootstrap()
#4 /var/www/GearmanManager/pecl-manager.php(219): GearmanManager->__construct()
#5 {main}
  thrown in /var/www/GearmanManager/pecl-manager.php on line 51

```

**Comment by kok888** [comment]
before  start thre gearmanClient with php ,we should ensure the gearmand Server is start and runing
